#!/bin/bash

# Install Python and Flask
sudo apt-get -y install python3-pip
sudo apt install python3.10-venv
sudo pip install flask
pip install python-dotenv

# Activate the enviroment  
sudo python3 -m venv myenv
source myenv/bin/activate

# Start the App
flask run
