#!/bin/bash

# Install Python and Flask
sudo apt-get install python3.9
sudo apt-get -y install python3-pip
sudo pip3 install -r requirements.txt
sudo apt-get update

# Use Docker Compose to start the app
sudo docker compose up -d

# Start the App
sudo flask run