services:
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=microblog
      - MYSQL_PASSWORD=mysqlserver
      - MYSQL_USER=microblog
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db:/var/lib/mysql
 
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
 
  flask:
    build: .
    container_name: flask
    restart: always
    environment:
        - DATABASE_URL=mysql+pymysql://microblog:mysqlserver@dbserver/microblog
    volumes:
      - ./app:/home/microblog/app:ro
    depends_on:
      - mysql
    links:
      - mysql:dbserver
Docker-File
FROM python:latest
 
RUN useradd microblog
 
WORKDIR /home/microblog
 
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
RUN venv/bin/pip install gunicorn pymysql cryptography
 
#COPY app app
RUN mkdir app
COPY migrations migrations
COPY microblog.py config.py boot.sh ./
COPY wsgi.py wsgi.py
RUN chmod a+x boot.sh
 
ENV FLASK_APP microblog.py
 
RUN chown -R microblog:microblog ./
USER microblog
 
EXPOSE 5000
ENTRYPOINT ["./boot.sh"]